export interface Module {
  id: string
  name: string
  icon: string
}

export const modules: Record<string, Module[]> = {
  html: [
    { id: 'inicio', name: 'Iniciando con HTML', icon: '/Apuntes/v2/icons/html.svg' },
    { id: 'titulosParrafos', name: 'Titulos & Parrafos', icon: '/Apuntes/v2/icons/texto.png' },
    { id: 'secciones', name: 'Secciones de Contenido', icon: '/Apuntes/v2/icons/contenido.png' },
    { id: 'bloqueLinea', name: 'Bloque vs Línea', icon: '/Apuntes/v2/icons/webpage.png' },
    { id: 'enlaces', name: 'Enlaces', icon: '/Apuntes/v2/icons/enlace.png' },
    { id: 'listas', name: 'Listas', icon: '/Apuntes/v2/icons/lista.png' },
    { id: 'tablas', name: 'Tablas', icon: '/Apuntes/v2/icons/tabla.png' },
    { id: 'formularios', name: 'Formularios', icon: '/Apuntes/v2/icons/formulario.png' },
    { id: 'embebido', name: 'Contenido Embebido', icon: '/Apuntes/v2/icons/contenidoEmbebido.png' },
    { id: 'meta', name: 'Meta', icon: '/Apuntes/v2/icons/meta.png' }
  ],
  css: [
    { id: 'fundamentos', name: 'Fundamentos CSS', icon: '/Apuntes/v2/icons/css.svg' },
    { id: 'medidas', name: 'Medidas y Unidades', icon: '/Apuntes/v2/icons/regla.png' },
    { id: 'boxmodel', name: 'Modelo de Caja', icon: '/Apuntes/v2/icons/caja.png' },
    { id: 'position', name: 'Posicionamiento', icon: '/Apuntes/v2/icons/position.png' },
    { id: 'boxalignment', name: 'Alineación', icon: '/Apuntes/v2/icons/alineacion.png' },
    { id: 'texto', name: 'Texto', icon: '/Apuntes/v2/icons/strings.png' },
    { id: 'visual', name: 'Efectos Visuales', icon: '/Apuntes/v2/icons/visual.png' },
    { id: 'background', name: 'Background', icon: '/Apuntes/v2/icons/imagen.png' },
    { id: 'pseudo', name: 'Pseudo Clases & Elementos', icon: '/Apuntes/v2/icons/pseudo.png' },
    { id: 'enlaces', name: 'Enlaces', icon: '/Apuntes/v2/icons/enlace.png' },
    { id: 'listas', name: 'Listas', icon: '/Apuntes/v2/icons/lista.png' },
  ],
  js: [
    { id: 'fundamentos', name: 'Fundamentos JS', icon: '/Apuntes/v2/icons/javascript.svg' },
    { id: 'strings', name: 'Strings', icon: '/Apuntes/v2/icons/strings.png' },
    { id: 'math', name: 'Math', icon: '/Apuntes/v2/icons/calculadora.png' },
    { id: 'condicionales', name: 'Condicionales', icon: '/Apuntes/v2/icons/condicionales.png' },
    { id: 'bucles', name: 'Bucles', icon: '/Apuntes/v2/icons/bucle.png' },
    { id: 'arrays', name: 'Arrays', icon: '/Apuntes/v2/icons/ArraysJS.png' },
    { id: 'spreadrest', name: 'Spread & Rest', icon: '/Apuntes/v2/icons/Spread.png' },
    { id: 'regex', name: 'Expresiones Regulares', icon: '/Apuntes/v2/icons/RegEx.png' },
    { id: 'poo', name: 'POO', icon: '/Apuntes/v2/icons/poo.png' },
    { id: 'dom', name: 'DOM', icon: '/Apuntes/v2/icons/web.png' },
    { id: 'eventos', name: 'Eventos', icon: '/Apuntes/v2/icons/eventos.png' },
  ],
  bootstrap: [
    { id: 'inicio', name: 'Iniciando con Bootstrap', icon: '/Apuntes/v2/icons/bootstrap.svg' },
    { id: 'imagenes', name: 'Imágenes', icon: '/Apuntes/v2/icons/imagen.png' },
    { id: 'tablas', name: 'Tablas', icon: '/Apuntes/v2/icons/tabla.png' },
    { id: 'botones', name: 'Botones', icon: '/Apuntes/v2/icons/botones.png' },
    { id: 'listgroup', name: 'List Group', icon: '/Apuntes/v2/icons/lista.png' },
    { id: 'cards', name: 'Cards', icon: '/Apuntes/v2/icons/card.png' },
    { id: 'carrusel', name: 'Carrusel', icon: '/Apuntes/v2/icons/carrusel.png' },
    { id: 'collapse', name: 'Collapse', icon: '/Apuntes/v2/icons/Collapse.png' },
    { id: 'dropdown', name: 'Dropdown', icon: '/Apuntes/v2/icons/dropdown.png' },
    { id: 'formularios', name: 'Formularios', icon: '/Apuntes/v2/icons/formulario.png' },
  ],
  typescript: [
    { id: 'inicio', name: '¿Qué es TS?', icon: '/Apuntes/v2/icons/typescript.svg' },
    { id: 'inferencia', name: 'Inferencia', icon: '/Apuntes/v2/icons/visual.png' },
    { id: 'tipos', name: 'Tipos de Datos', icon: '/Apuntes/v2/icons/datos.png' },
    { id: 'funciones', name: 'Funciones', icon: '/Apuntes/v2/icons/funciones.png' },
    { id: 'arrays', name: 'Arrays & Tuplas', icon: '/Apuntes/v2/icons/arraysTS.png' },
    { id: 'enums', name: 'Enums', icon: '/Apuntes/v2/icons/funciones.png' },
    { id: 'poo', name: 'POO', icon: '/Apuntes/v2/icons/poo.png' },
    { id: 'genericos', name: 'Genéricos', icon: '/Apuntes/v2/icons/visual.png' },
    { id: 'utilidad', name: 'Tipos de Utilidad', icon: '/Apuntes/v2/icons/visual.png' },
  ],
  nodejs: [
    { id: 'inicio', name: '¿Qué es Node.js?', icon: '/Apuntes/v2/icons/node.svg' },
    { id: 'filesystem', name: 'File System', icon: '/Apuntes/v2/icons/file.png' },
    { id: 'path', name: 'Path', icon: '/Apuntes/v2/icons/path.png' },
    { id: 'process', name: 'Objeto Process', icon: '/Apuntes/v2/icons/process.png' },
    { id: 'npm', name: 'NPM', icon: '/Apuntes/v2/icons/NPM.png' },
    { id: 'envvars', name: 'Variables de Entorno', icon: '/Apuntes/v2/icons/enviroment.png' },
    { id: 'http', name: 'Módulo HTTP', icon: '/Apuntes/v2/icons/http.png' },
    { id: 'express', name: 'Express', icon: '/Apuntes/v2/icons/Framework.png' },
    { id: 'apirest', name: 'API REST', icon: '/Apuntes/v2/icons/http.png' },
    { id: 'zod', name: 'Zod', icon: '/Apuntes/v2/icons/zod.webp' },
  ],
}
